#ifndef _DEV_SIGN_CONFIG_H_
#define _DEV_SIGN_CONFIG_H_

#define DEV_SIGN_SOURCE_MAXLEN    (200)
#define DEV_SIGN_HOSTNAME_MAXLEN  (64)
#define DEV_SIGN_CLIENT_ID_MAXLEN (200)
#define DEV_SIGN_USERNAME_MAXLEN  (64)
#define DEV_SIGN_PASSWORD_MAXLEN  (65)

#endif

