#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#
PROJECT_NAME := esp_fastbee_aliyun

EXTRA_COMPONENT_DIRS := $(realpath ./esp-aliyun)

SDKCONFIG_DEFAULTS := sdkconfig_$(chip).defaults

include $(IDF_PATH)/make/project.mk